/*******************************************************************************
 * Copyright (C) 2016 Mango Business Solutions Ltd, http://www.mango-solutions.com
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 *******************************************************************************/
package eu.ddmore.convertertoolbox.api.response;

import java.util.Map;

/**
 * Bean representing details generated by a conversion activity
 */
public interface ConversionDetail {
	
	/**
	 * Models the severity levels.
	 */
	public enum Severity {
		ERROR(1), WARNING(2), INFO(3), DEBUG(4), ALL(5);
		private int rank;
		private Severity(int rank) {
		    this.rank = rank;
		}
		public int getRank() {
		    return rank;
		}
	}

    /**
     * @return the severity level associated with this ConversionDetail
     */
    Severity getServerity();

    /**
     * Sets the severity level.
     * @param severity the severity level to set
     */
    void setSeverity(Severity severity);

    /**
     * @return the map representing the information associated with this ConversionDetail
     */
    Map<String, String> getInfo();

    /**
     * Sets the information map.
     * @param info the information map to set
     */
    void setInfo(Map<String, String> info);

    /**
     * Adds key-value pair on the information map associated with this ConversionDetail.
     * @param key the key of the information to add
     * @param value the value of the information to add
     */
    void addInfo(String key, String value);

    /**
     * @return the message associated with this ConversionDetail
     */
    String getMessage();

    /**
     * Sets the message associated with this ConversionDetail.
     * @param message the message to set
     */
    void setMessage(String message);
}
